### ISSUE TITLE
web page errors saection 9.1.3.3

### ISSUE THREAD

**Issue by Lloydf** [ROBOTIS-GIT/open_manipulator_processing#7]
command missing (roslaunch)
($ open_manipulator_ar_markers ar_pose.launch camera_model:=raspicam user_marker_size:=3.0)
It should be: $ roslaunch open_manipulator_ar_markers ar_pose.launch camera_model:=realsense_d435 user_marker_size:=3.0
but even this will not work becaus the rviz is coded for rpi camera. Needs much work here,
video was removed, whole example is hum... not working...

**Comment by yhna** [comment]
@Lloydf 

Sorry for the late response.

Section 9.1.3 of e-manual is an example using rpi camera. To use the realsense d435, you must manually modify the parameters, such as ros msg name
